mode: 'train'
ARCHITECTURE:
    name: 'DLA60'

pretrained_model: ""
model_save_dir: "./output/"
classes_num: 1000
total_images: 1281167
save_interval: 1
validate: True
valid_interval: 1
epochs: 120
topk: 5
image_shape: [3, 224, 224]

use_mix: True
ls_epsilon: 0.1

LEARNING_RATE:
   function: 'CosineWarmup'
   params:
       lr: 0.04

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.000100

TRAIN:
    batch_size: 512
    num_workers: 4
    file_list: "/dataset/public/ImageNetOrigin/list_train.txt"
    data_dir: "/dataset/public/ImageNetOrigin/train/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - RandCropImage:
            size: 224
            interpolation: 2
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
    mix:
        - MixupOperator:
            alpha: 0.2

VALID:
    batch_size: 128
    num_workers: 0
    file_list: "/home/aistudio/data/data68594/val_list.txt"
    data_dir: "/home/aistudio/data/data68594/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            interpolation: 2
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
