TrainReader:
  inputs_def:
    # fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_segm']
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_segm', 'gt_num']
  dataset:
    !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  # - !RandomDistort
  #   brightness_lower: 0.875
  #   brightness_upper: 1.125
  #   is_order: true
  # - !ExpandImage
  #   max_ratio: 4
  #   prob: 0.5
  #   segm_flag: true
  # - !RandomCrop
  #   allow_no_crop: true
  - !RandomMirror {}
  - !ResizeImage
    target_size: 550
    # max_size: 550
    interp: 1
    use_cv2: true
  - !PadBox
    num_max_boxes: 50
  - !Permute
    to_bgr: false
    channel_first: true
  - !Pad
    mean: [123.68, 116.78, 103.94]
    width: 550
    height: 550
  - !NormalizeImage
    is_channel_first: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
  - !ToPercentCoords {}
#   - !PrepareMasks {}
  batch_size: 8
  bufsize: 1
  shuffle: true
  worker_num: 8
  use_process: false
  load_segm: true
  drop_last: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
    # for voc
    #fields: ['image', 'im_info', 'im_id',  'im_shape', 'gt_bbox', 'gt_class', 'is_difficult']
  dataset:
    !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco
  sample_transforms:
  - !DecodeImage
    to_rgb: true
#   - !NormalizeImage
#     is_channel_first: false
#     is_scale: false
#     mean: [123.68, 116.78, 103.94]
#     std: [58.40, 57.12, 57.38]
    # mean: [0.485,0.456,0.406]
    # std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    target_size: 550
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  - !NormalizeImage
    is_channel_first: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
  batch_size: 1
  bufsize: 1
  shuffle: false
  worker_num: 1
  use_process: false
  load_segm: false 

TestReader:
  inputs_def:
    # set image_shape if needed
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: annotations/instances_val2017.json
  sample_transforms:
  sample_transforms:
  - !DecodeImage
    to_rgb: false
    with_mixup: false
#   - !NormalizeImage
#     is_channel_first: false
#     is_scale: false
#     mean: [123.68, 116.78, 103.94]
#     std: [58.40, 57.12, 57.38]
    # mean: [0.485,0.456,0.406]
    # std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    target_size: 550
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  - !NormalizeImage
    is_channel_first: true
    is_scale: false
    mean: [103.94, 116.78, 123.68]
    std: [57.38, 57.12, 58.40]
  batch_size: 1
