architecture: Yolactplus
max_iters: 1050000
use_gpu: true
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
weights: output/yolactplus_r50_fpn/1020000
log_smooth_window: 10
snapshot_iter: 10000
metric: COCO
save_dir: output
num_classes: 81

Yolactplus:
  backbone: ResNet
  fpn: FPN
  yolact_head: YolactHead
  
ResNet:
  depth: 50
  feature_maps: [3, 4, 5]
  freeze_at: 0
  norm_type: bn
  freeze_norm: false
  variant: b
  dcn_v2_stages: [3, 4, 5]

# ResNet:
#   depth: 50
#   norm_type: bn
#   feature_maps: [3, 4, 5]
#   freeze_at: 2
#   dcn_v2_stages: [3, 4, 5]

# ResNet:
#   norm_type: affine_channel
#   norm_decay: 0.
#   depth: 50
#   feature_maps: [3, 4, 5]
#   freeze_at: 2
 
FPN:
  max_level: 7
  min_level: 3
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125]
  has_extra_convs: true

YolactHead:
  anchor_generator:
    aspect_ratios: [1.0, 2.0, 0.5]
    variance: [1.0, 1.0, 1.0, 1.0]
  num_chan: 256
  max_level: 7
  min_level: 3
  num_classes: 80
  batch_size: 8

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [300000, 750000, 850000, 950000]
  - !LinearWarmup
    start_factor: 0.1
    steps: 5000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0000
    type: L2

_READER_: 'yolactplus_reader.yml'
# _READER_: 'faster_fpn_reader.yml'
TrainReader:
  batch_size: 8

EvalReader:
  batch_size: 1

TestReader:
  batch_size: 1