base_lr: 0.1
batch_size: 64
config: work/2s_AGCN/config/nturgbd-cross-view/train_bone.yaml
device:
- gpu:0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: paddle_model.agcn.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cv_agcn_bone
nesterov: true
num_epoch: 50
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 29
- 39
test_batch_size: 64
test_feeder_args:
  data_path: xview/val_data_bone.npy
  debug: false
  label_path: xview/val_label.pkl
train_feeder_args:
  data_path: xview/train_data_bone.npy
  debug: false
  label_path: xview/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 0
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/ntu/xview/agcn_bone
